# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2Gbl0rPpTOr8Ee4wKA86fNbVpG9gXEB
"""

def converter(celsius):
  return (celsius * 9/5) + 32

try:
  temperatura = float(input("Insira a temperatura em celsius: "))
except ValueError:
  print("Insira numeros, isso não é uma string.")
else:
  print(f"{temperatura}°C é {converter(temperatura)}°F")

